//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.PlayerPositions = new HashSet<PlayerPosition>();
        }
    
        public int PositionID { get; set; }
        public Nullable<int> PositionTypeID { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> MaxCount { get; set; }
        public string PositionNameLong { get; set; }
        public Nullable<int> PositionSortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerPosition> PlayerPositions { get; set; }
        public virtual PositionType PositionType { get; set; }
    }
}
