//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        public int StatID { get; set; }
        public string StatName { get; set; }
        public Nullable<int> PositionTypeID { get; set; }
    
        public virtual PositionType PositionType { get; set; }
    }
}
