//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.SeasonTeams = new HashSet<SeasonTeam>();
            this.SeasonTeamPlayers = new HashSet<SeasonTeamPlayer>();
            this.SeasonTeamStadiums = new HashSet<SeasonTeamStadium>();
            this.TradeTeams = new HashSet<TradeTeam>();
            this.TradeTeamDetails = new HashSet<TradeTeamDetail>();
            this.TradeTeamDetails1 = new HashSet<TradeTeamDetail>();
        }
    
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.Guid> OwnerUserID { get; set; }
        public string OwnerEmail { get; set; }
        public byte[] TeamImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonTeam> SeasonTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonTeamPlayer> SeasonTeamPlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeasonTeamStadium> SeasonTeamStadiums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeTeam> TradeTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeTeamDetail> TradeTeamDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradeTeamDetail> TradeTeamDetails1 { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
