//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeTeamDetail
    {
        public int SeasonID { get; set; }
        public System.Guid TradeGUID { get; set; }
        public int TeamID { get; set; }
        public System.Guid PlayerGUID { get; set; }
        public Nullable<int> TeamIDTarget { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual TradeTeam TradeTeam { get; set; }
    }
}
